/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Nvm = {
  badge?: string
  title?: string
  body?: string
  cta?: Cta
}

export type Person = {
  initials?: string
  name?: string
  role?: string
  links?: Array<{
    label?: string
    link?: Link
    _key: string
  }>
}

export type Aside = {
  title?: string
  body?: string
  items?: Array<{
    icon?: 'phone' | 'whatsapp' | 'mail' | 'pin'
    title?: string
    subtitle?: string
    _key: string
  }>
  cta?: Cta
}

export type AanbodHeaderAside = {
  title?: string
  body?: string
  cta?: Cta
}

export type CtaCard = {
  title?: string
  body?: string
  cta?: Cta
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type ItemsObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "items.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type TimelineItemsObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "timeline.items.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type Werkwijze = {
  _type: 'werkwijze'
  eyebrow?: string
  title?: string
  lead?: string
  items?: Array<{
    number?: string
    title?: string
    body?: string
    _key: string
  }>
}

export type ReviewGrid = {
  _type: 'reviewGrid'
  title?: string
  more?: string
  empty?: string
}

export type ReviewReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'review'
}

export type UitgelichteReview = {
  _type: 'uitgelichteReview'
  eyebrow?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  review?: ReviewReference
}

export type BeoordelingenHero = {
  _type: 'beoordelingenHero'
  breadcrumbLabel?: string
  eyebrow?: string
  title?: string
  titleHighlight?: string
  lead?: string
  primaryCta?: Cta
  secondaryCta?: Cta
  scoreLabel?: string
  scoreNote?: string
}

export type ObjectGrid = {
  _type: 'objectGrid'
  ctaCard?: CtaCard
  emptyTitle?: string
  emptyBody?: string
}

export type AanbodHeader = {
  _type: 'aanbodHeader'
  breadcrumbLabel?: string
  eyebrow?: string
  title?: string
  titleHighlight?: string
  lead?: string
  aside?: AanbodHeaderAside
}

export type RouteBlock = {
  _type: 'routeBlock'
  eyebrow?: string
  title?: string
  lead?: string
  columns?: Array<{
    title?: string
    body?: string
    _key: string
  }>
  cta?: Cta
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type ContactFormReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'contactForm'
}

export type ContactFormSection = {
  _type: 'contactFormSection'
  eyebrow?: string
  title?: string
  lead?: string
  form?: ContactFormReference
  note?: string
  successTitle?: string
  successBody?: string
  aside?: Aside
}

export type PersonBlock = {
  _type: 'personBlock'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  eyebrow?: string
  title?: string
  body?: string
  person?: Person
}

export type ContactWays = {
  _type: 'contactWays'
  items?: Array<{
    icon?: 'phone' | 'whatsapp' | 'mail' | 'pin'
    title?: string
    body?: string
    value?: string
    note?: string
    link?: Link
    _key: string
  }>
}

export type SplitHero = {
  _type: 'splitHero'
  breadcrumbLabel?: string
  eyebrow?: string
  title?: string
  titleHighlight?: string
  lead?: string
  primaryCta?: Cta
  secondaryCta?: Cta
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type CompareCards = {
  _type: 'compareCards'
  eyebrow?: string
  title?: string
  lead?: string
  cards?: Array<{
    label?: string
    title?: string
    body?: string
    items?: Array<{
      text?: string
      included?: boolean
      _key: string
    }>
    cta?: Cta
    dark?: boolean
    _key: string
  }>
}

export type Assurances = {
  _type: 'assurances'
  eyebrow?: string
  title?: string
  lead?: string
  items?: Array<{
    title?: string
    body?: string
    _key: string
  }>
}

export type MediaText = {
  _type: 'mediaText'
  eyebrow?: string
  title?: string
  paragraphs?: Array<string>
  cta?: Cta
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type ValueCards = {
  _type: 'valueCards'
  eyebrow?: string
  title?: string
  lead?: string
  items?: Array<{
    icon?: 'heart' | 'rings' | 'lines'
    title?: string
    body?: string
    _key: string
  }>
}

export type Timeline = {
  _type: 'timeline'
  eyebrow?: string
  title?: string
  lead?: string
  items?: Array<{
    year?: string
    title?: string
    body?: string
    image?: TimelineItemsObjectImage
    _key: string
  }>
}

export type DuoPhotos = {
  _type: 'duoPhotos'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  stampValue?: string
  stampLabel?: string
  secondaryImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  caption?: string
}

export type PageOpener = {
  _type: 'pageOpener'
  eyebrow?: string
  title?: string
  titleHighlight?: string
  lead?: string
  motto?: string
  attribution?: string
}

export type CrossLinks = {
  _type: 'crossLinks'
  items?: Array<{
    title?: string
    body?: string
    link?: Link
    _key: string
  }>
}

export type RegionBlock = {
  _type: 'regionBlock'
  eyebrow?: string
  title?: string
  lead?: string
  places?: Array<{
    label?: string
    link?: Link
    _key: string
  }>
}

export type FaqReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'faq'
}

export type Faqs = {
  _type: 'faqs'
  eyebrow?: string
  title?: string
  intro?: string
  link?: Cta
  faqs?: Array<
    {
      _key: string
    } & FaqReference
  >
}

export type QuoteBand = {
  _type: 'quoteBand'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  eyebrow?: string
  quote?: string
  initials?: string
  name?: string
  place?: string
}

export type Steps = {
  _type: 'steps'
  eyebrow?: string
  title?: string
  lead?: string
  cta?: Cta
  items?: Array<{
    number?: string
    title?: string
    body?: string
    image?: ItemsObjectImage
    _key: string
  }>
}

export type Benefits = {
  _type: 'benefits'
  eyebrow?: string
  title?: string
  lead?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  items?: Array<{
    icon?: 'person' | 'camera' | 'chart' | 'doc' | 'house' | 'renovate' | 'scale'
    title?: string
    body?: string
    _key: string
  }>
}

export type FactBar = {
  _type: 'factBar'
  facts?: Array<{
    value?: string
    label?: string
    _key: string
  }>
}

export type PageHero = {
  _type: 'pageHero'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  breadcrumbLabel?: string
  eyebrow?: string
  title?: string
  titleHighlight?: string
  lead?: string
  primaryCta?: Cta
  secondaryCta?: Cta
}

export type CtaBand = {
  _type: 'ctaBand'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  eyebrow?: string
  title?: string
  body?: string
  primaryCta?: Cta
  secondaryCta?: Cta
}

export type Listings = {
  _type: 'listings'
  title?: string
  cta?: Cta
  regionsLabel?: string
  regions?: Array<{
    label?: string
    link?: Link
    _key: string
  }>
}

export type Reviews = {
  _type: 'reviews'
  score?: string
  scoreLabel?: string
  reviewCountLabel?: string
  intro?: string
  showGrades?: boolean
  link?: Cta
}

export type Story = {
  _type: 'story'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  secondaryImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  eyebrow?: string
  title?: string
  quote?: string
  attribution?: string
  cta?: Cta
}

export type Services = {
  _type: 'services'
  title?: string
  lead?: string
  items?: Array<{
    label?: string
    title?: string
    description?: string
    image?: ObjectImage
    link?: Link
    _key: string
  }>
  nvm?: Nvm
}

export type Intro = {
  _type: 'intro'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  stampValue?: string
  stampLabel?: string
  eyebrow?: string
  title?: string
  titleHighlight?: string
  leads?: Array<string>
  facts?: Array<{
    value?: string
    label?: string
    _key: string
  }>
  link?: Cta
}

export type Hero = {
  _type: 'hero'
  slides?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  eyebrow?: string
  title?: string
  titleHighlight?: string
  lead?: string
  primaryCta?: Cta
  secondaryCta?: Cta
  badgeLabel?: string
}

export type PageBuilder = Array<
  | ({
      _key: string
    } & Hero)
  | ({
      _key: string
    } & Intro)
  | ({
      _key: string
    } & Services)
  | ({
      _key: string
    } & Story)
  | ({
      _key: string
    } & Reviews)
  | ({
      _key: string
    } & Listings)
  | ({
      _key: string
    } & CtaBand)
  | ({
      _key: string
    } & PageHero)
  | ({
      _key: string
    } & FactBar)
  | ({
      _key: string
    } & Benefits)
  | ({
      _key: string
    } & Steps)
  | ({
      _key: string
    } & QuoteBand)
  | ({
      _key: string
    } & Faqs)
  | ({
      _key: string
    } & RegionBlock)
  | ({
      _key: string
    } & CrossLinks)
  | ({
      _key: string
    } & PageOpener)
  | ({
      _key: string
    } & DuoPhotos)
  | ({
      _key: string
    } & Timeline)
  | ({
      _key: string
    } & ValueCards)
  | ({
      _key: string
    } & MediaText)
  | ({
      _key: string
    } & Assurances)
  | ({
      _key: string
    } & CompareCards)
  | ({
      _key: string
    } & SplitHero)
  | ({
      _key: string
    } & ContactWays)
  | ({
      _key: string
    } & PersonBlock)
  | ({
      _key: string
    } & ContactFormSection)
  | ({
      _key: string
    } & RouteBlock)
  | ({
      _key: string
    } & AanbodHeader)
  | ({
      _key: string
    } & ObjectGrid)
  | ({
      _key: string
    } & BeoordelingenHero)
  | ({
      _key: string
    } & UitgelichteReview)
  | ({
      _key: string
    } & ReviewGrid)
  | ({
      _key: string
    } & Werkwijze)
>

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Cta = {
  _type: 'cta'
  label?: string
  linkType?: 'internal' | 'external'
  internalLink?: PageReference
  href?: string
}

export type Link = {
  _type: 'link'
  linkType?: 'internal' | 'external'
  internalLink?: PageReference
  href?: string
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  noIndex?: boolean
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  paragraph?: string
  socialLinks?: Array<{
    platform?: 'facebook' | 'instagram' | 'linkedin'
    url?: string
    _type: 'socialLink'
    _key: string
  }>
  linkGroups?: Array<{
    title?: string
    links?: Array<{
      label?: string
      linkType?: 'internal' | 'external'
      internalLink?: PageReference
      href?: string
      _type: 'footerLink'
      _key: string
    }>
    _type: 'linkGroup'
    _key: string
  }>
  copyright?: string
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  navLeft?: Array<{
    label?: string
    linkType?: 'internal' | 'external'
    internalLink?: PageReference
    href?: string
    _type: 'navLink'
    _key: string
  }>
  navRight?: Array<{
    label?: string
    linkType?: 'internal' | 'external'
    internalLink?: PageReference
    href?: string
    _type: 'navLink'
    _key: string
  }>
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type Woning = {
  _id: string
  _type: 'woning'
  _createdAt: string
  _updatedAt: string
  _rev: string
  realworksId?: number
  adres?: string
  slug?: Slug
  postcode?: string
  plaats?: string
  status?: 'beschikbaar' | 'voorbehoud' | 'verkocht'
  prijs?: number
  prijsConditie?: 'k.k.' | 'v.o.n.'
  aangebodenSinds?: string
  aanvaarding?: string
  soortWoning?: string
  bouwjaar?: number
  woonoppervlak?: number
  perceel?: number
  inhoud?: number
  kamers?: number
  slaapkamers?: number
  energielabel?: 'A+++' | 'A++' | 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G'
  kenmerkGroepen?: Array<{
    titel?: string
    rijen?: Array<{
      label?: string
      waarde?: Array<string>
      _type: 'kenmerk'
      _key: string
    }>
    _type: 'kenmerkGroep'
    _key: string
  }>
  aanbiedingsTekst?: string
  aanbiedingsTekstEngels?: string
  fotos?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  brochure?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Review = {
  _id: string
  _type: 'review'
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote?: string
  name?: string
  type?: 'Aankoop' | 'Verkoop'
  date?: string
  grade?: number
  accessibilityAndCommunication?: number
  expertise?: number
  localMarketKnowledge?: number
  negotiationAndResult?: number
  priceQuality?: number
  serviceAndGuidance?: number
  fundaKey?: string
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  answer?: string
  link?: Cta
  afterLink?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  seo?: Seo
  content?: PageBuilder
}

export type FormGeneralSettings = {
  _id: string
  _type: 'formGeneralSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  adminEmail?: string
  smtpUsername?: string
  smtpPassword?: string
  successMessage?: string
  confirmationSubject?: string
  confirmationMessage?: string
  recaptchaEnabled?: boolean
  recaptchaSiteKey?: string
  recaptchaSecretKey?: string
}

export type ContactForm = {
  _id: string
  _type: 'contactForm'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  showtitle?: boolean
  id?: string
  class?: string
  fields?: Array<{
    label?: string
    type?: 'text' | 'email' | 'tel' | 'textarea' | 'url' | 'file' | 'checkbox' | 'select' | 'radio'
    showPlaceholder?: boolean
    placeholder?: string
    name?: string
    selectOptions?: Array<string>
    radioOptions?: Array<string>
    checkboxOptions?: Array<string>
    helpText?: string
    note?: string
    isRequired?: boolean
    _key: string
  }>
  submitButtonText?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Nvm
  | Person
  | Aside
  | AanbodHeaderAside
  | CtaCard
  | SanityImageAssetReference
  | ObjectImage
  | ItemsObjectImage
  | TimelineItemsObjectImage
  | Werkwijze
  | ReviewGrid
  | ReviewReference
  | UitgelichteReview
  | BeoordelingenHero
  | ObjectGrid
  | AanbodHeader
  | RouteBlock
  | ContactFormReference
  | ContactFormSection
  | PersonBlock
  | ContactWays
  | SplitHero
  | CompareCards
  | Assurances
  | MediaText
  | ValueCards
  | Timeline
  | DuoPhotos
  | PageOpener
  | CrossLinks
  | RegionBlock
  | FaqReference
  | Faqs
  | QuoteBand
  | Steps
  | Benefits
  | FactBar
  | PageHero
  | CtaBand
  | Listings
  | Reviews
  | Story
  | Services
  | Intro
  | Hero
  | PageBuilder
  | PageReference
  | Cta
  | Link
  | Seo
  | Footer
  | Navigation
  | SanityFileAssetReference
  | Woning
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Review
  | Faq
  | Page
  | FormGeneralSettings
  | ContactForm
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
