import {defineArrayMember, defineType} from 'sanity'

export const pageBuilderType = defineType({
  name: 'pageBuilder',
  type: 'array',
  of: [
    defineArrayMember({type: 'hero'}),
    defineArrayMember({type: 'intro'}),
    defineArrayMember({type: 'services'}),
    defineArrayMember({type: 'story'}),
    defineArrayMember({type: 'reviews'}),
    defineArrayMember({type: 'listings'}),
    defineArrayMember({type: 'ctaBand'}),
    defineArrayMember({type: 'pageHero'}),
    defineArrayMember({type: 'factBar'}),
    defineArrayMember({type: 'benefits'}),
    defineArrayMember({type: 'steps'}),
    defineArrayMember({type: 'quoteBand'}),
    defineArrayMember({type: 'faqs'}),
    defineArrayMember({type: 'regionBlock'}),
    defineArrayMember({type: 'crossLinks'}),
    defineArrayMember({type: 'pageOpener'}),
    defineArrayMember({type: 'duoPhotos'}),
    defineArrayMember({type: 'timeline'}),
    defineArrayMember({type: 'valueCards'}),
    defineArrayMember({type: 'mediaText'}),
    defineArrayMember({type: 'assurances'}),
    defineArrayMember({type: 'compareCards'}),
    defineArrayMember({type: 'splitHero'}),
    defineArrayMember({type: 'contactWays'}),
    defineArrayMember({type: 'personBlock'}),
    defineArrayMember({type: 'contactFormSection'}),
    defineArrayMember({type: 'routeBlock'}),
    defineArrayMember({type: 'highlightStrip'}),
    defineArrayMember({type: 'aanbodHeader'}),
    defineArrayMember({type: 'objectGrid'}),
    defineArrayMember({type: 'beoordelingenHero'}),
    defineArrayMember({type: 'uitgelichteReview'}),
    defineArrayMember({type: 'reviewGrid'}),
    defineArrayMember({type: 'werkwijze'}),
    defineArrayMember({type: 'formHero'}),
    defineArrayMember({type: 'iconCards'}),
    defineArrayMember({type: 'numberedSteps'}),
    defineArrayMember({type: 'personQuote'}),
    defineArrayMember({type: 'quoteStrip'}),
    defineArrayMember({type: 'centeredCta'}),
    defineArrayMember({type: 'richText'}),
  ],
})
